### ISSUE TITLE
Failed with error: {"message":"Cannot read properties of undefined (reading 'replace')"}

### ISSUE THREAD

**Issue by nithi2023** [facundoolano/google-play-api#83] opened 2023-01-07 19:03 UTC
I have tried an app details endpoint: `http://localhost:443/api/apps/org.wikipedia/?lang=es`

and got this error: `{"message":"Cannot read properties of undefined (reading 'replace')"}`

I could't able to figure out the issue.

**Comment by nathannli** [comment] 2023-02-15 20:49
did you try using this fix?
https://github.com/facundoolano/google-play-api/pull/76

**Comment by canalamh2** [comment] 2023-06-14 23:39
mesmo erro

**Comment by ucf0709** [comment] 2023-09-29 19:27
go to project root : node_modules\google-play-scraper\lib\app.js

replace all ds:4 with  ds:5
then replace ds:8 with ds:9

**Comment by jaredsburrows** [comment] 2024-02-06 14:48
This is a duplicate of https://github.com/facundoolano/google-play-api/issues/28.

**Comment by facundoolano** [comment] 2024-02-06 16:04
should be fixed on latest version

**Closed by facundoolano** 2024-02-06 16:04 UTC
